services:
  database:
          image: postgres:14-alpine
          container_name: db_padawan
          user: postgres
          ports: 
            - "5432:5432"
          networks:
            - app-network
          environment:
            POSTGRES_DB: "projetoFramelab"
            POSTGRES_USER: "padawanAdm"
            POSTGRES_PASSWORD: teste
  backend:
      build:
          dockerfile: ./config/Dockerfile
      container_name: framelabApi
      command: node_modules/.bin/nodemon --exec npm start
      networks:
          - app-network
      ports:
          - "3002:3002"
      environment:
        DB_HOST: db_padawan
        
networks:
    app-network:
        driver: bridge